In [4]:
import numpy as np

A = np.arange(1, 16).reshape(3, 5)

print("Dimensions (ndim):", A.ndim)  # number of axes
print("Shape:", A.shape)  # shape of the matrix
print("Size:", A.size)  # total number of elements
print("Data Type:", A.dtype)  # data type of the elements


Dimensions (ndim): 2
Shape: (3, 5)
Size: 15
Data Type: int32


## Exercise 1

## Exercise 2

In [6]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [7]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3)) * 2

print("Elementwise Subtraction:")
print(B - C)

print("\nElementwise Multiplication:")
print(B * C)

print("\nMatrix Multiplication:")
print(B @ C)


Elementwise Subtraction:
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

Elementwise Multiplication:
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

Matrix Multiplication:
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


## Exercise 3

In [8]:
B = np.arange(1, 10).reshape(3, 3)

print("Exponentiation (elementwise):")
print(np.exp(B))

print("\nMinimum value in the matrix:")
print(np.min(B))

print("\nMinimum value in each row:")
print(np.min(B, axis=1))

print("\nMinimum value in each column:")
print(np.min(B, axis=0))

print("\nIndex of the minimum value in the matrix:")
print(np.argmin(B))

print("\nIndex of the minimum value in each row:")
print(np.argmin(B, axis=1))

print("\nSum of all elements:")
print(np.sum(B))

print("\nMean for each column:")
print(np.mean(B, axis=0))

print("\nMedian for each column:")
print(np.median(B, axis=0))


Exponentiation (elementwise):
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

Minimum value in the matrix:
1

Minimum value in each row:
[1 4 7]

Minimum value in each column:
[1 2 3]

Index of the minimum value in the matrix:
0

Index of the minimum value in each row:
[0 0 0]

Sum of all elements:
45

Mean for each column:
[4. 5. 6.]

Median for each column:
[4. 5. 6.]


## Exercise 4

In [10]:
A = np.arange(1, 16).reshape(3, 5)
print("Matrix A:")
print(A)

print("\nSlicing with fewer indices (A[1]):")
print(A[1])


Matrix A:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

Slicing with fewer indices (A[1]):
[ 6  7  8  9 10]


## Exercise 5

In [12]:
A = np.arange(1, 16).reshape(3, 5)
print("Matrix A:")
print(A)

print("\nIterating over all elements elementwise:")
for element in np.nditer(A):
    print(element, end=" ")


Matrix A:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

Iterating over all elements elementwise:
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 

## Exercise 6

In [13]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [14]:
a = np.arange(30)
b = a.reshape((2, 3, -1))

print("Array a:")
print(a)

print("\nReshaped Array b:")
print(b)


Array a:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

Reshaped Array b:
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


## Exercise 7

In [15]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


In [16]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])

print("Matrix m1:")
print(m1)

print("\nMatrix m2:")
print(m2)

print("\nm1 + m2 (with broadcasting):")
print(m1 + m2)


Matrix m1:
[[1 2]
 [3 4]]

Matrix m2:
[1 1]

m1 + m2 (with broadcasting):
[[2 3]
 [4 5]]


## Exercise 8

In [17]:
def add_mult_matrices(matrix1, matrix2, operation):
    if not isinstance(matrix1, np.ndarray) or not isinstance(matrix2, np.ndarray):
        raise TypeError("Both inputs must be numpy arrays")
    
    if operation not in ['add', 'multiply']:
        raise ValueError("Operation must be 'add' or 'multiply'")
    
    if operation == 'add':
        if matrix1.shape != matrix2.shape:
            raise ValueError("Matrices must have the same shape for addition")
        return matrix1 + matrix2
    
    if operation == 'multiply':
        if matrix1.shape[1] != matrix2.shape[0]:
            raise ValueError("For multiplication, the number of columns in the first matrix must equal the number of rows in the second matrix")
        return matrix1 @ matrix2

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

print("Matrix Addition:")
print(add_mult_matrices(matrix1, matrix2, 'add'))

print("\nMatrix Multiplication:")
print(add_mult_matrices(matrix1, matrix2, 'multiply'))


Matrix Addition:
[[ 6  8]
 [10 12]]

Matrix Multiplication:
[[19 22]
 [43 50]]


## övningsuppgifter 10.1.1
 ### matematik för yerkshögskolan

In [1]:
import numpy as np

# Defining vector x
x = np.array([4, 3])

# (a) What is the dimension of vector x?
dimension_x = x.shape

# (b) Calculate 5x
result_5x = 5 * x

# (c) Calculate 3x
result_3x = 3 * x

# (d) Calculate 5x + 3x
result_5x_plus_3x = 5 * x + 3 * x

# (e) Calculate 8x
result_8x = 8 * x

# (f) Calculate 4x - x
result_4x_minus_x = 4 * x - x

# (g) Calculate x^T (transpose of x) and its new dimension
transpose_x = x.T
dimension_transpose_x = transpose_x.shape

# (h) Is x + x^T defined?
# In NumPy, this is just element-wise addition, so it is defined.
is_x_plus_xT_defined = True  # It is always defined in this case

# (i) Calculate ||x|| (the norm of x)
norm_x = np.linalg.norm(x)

# Printing results
print("Dimension of x:", dimension_x)
print("5x:", result_5x)
print("3x:", result_3x)
print("5x + 3x:", result_5x_plus_3x)
print("8x:", result_8x)
print("4x - x:", result_4x_minus_x)
print("Transpose of x:", transpose_x)
print("Dimension of transpose x:", dimension_transpose_x)
print("Is x + x^T defined?", is_x_plus_xT_defined)
print("||x|| (Norm of x):", norm_x)


Dimension of x: (2,)
5x: [20 15]
3x: [12  9]
5x + 3x: [32 24]
8x: [32 24]
4x - x: [12  9]
Transpose of x: [4 3]
Dimension of transpose x: (2,)
Is x + x^T defined? True
||x|| (Norm of x): 5.0


## uppgift 10.1.2

In [4]:
import numpy as np

# Defining vector v
v = np.array([3, 7, 0, 11])

# (a) What is the dimension of vector v?
dimension_v = v.shape

# (b) Calculate 2v
result_2v = 2 * v

# (c) Calculate 5v + 2v
result_5v_plus_2v = 5 * v + 2 * v

# (d) Calculate 4v - 2v
result_4v_minus_2v = 4 * v - 2 * v

# (e) Calculate v^T (transpose of v) and its new dimension
# For 1D vectors in NumPy, the transpose does not change the shape,
# so transpose has no effect on 1D vectors.
transpose_v = v.T
dimension_transpose_v = transpose_v.shape

# (f) Calculate ||v|| (the norm of v)
norm_v = np.linalg.norm(v)

# Printing results
print("Dimension of v:", dimension_v)
print("2v:", result_2v)
print("5v + 2v:", result_5v_plus_2v)
print("4v - 2v:", result_4v_minus_2v)
print("Transpose of v:", transpose_v)
print("Dimension of transpose v:", dimension_transpose_v)
print("||v|| (Norm of v):", norm_v)


Dimension of v: (4,)
2v: [ 6 14  0 22]
5v + 2v: [21 49  0 77]
4v - 2v: [ 6 14  0 22]
Transpose of v: [ 3  7  0 11]
Dimension of transpose v: (4,)
||v|| (Norm of v): 13.379088160259652


## uppgift 10.1.3

In [6]:
# Defining vectors v1 and v2
v1 = np.array([4, 3, 1, 5])
v2 = np.array([2, 3, 1, 1])

# (a) Calculate ||v1|| (the norm of v1)
norm_v1 = np.linalg.norm(v1)

# (b) Calculate ||v1 - v2|| (the norm of the difference between v1 and v2)
norm_v1_minus_v2 = np.linalg.norm(v1 - v2)

# Printing results
print("||v1|| (Norm of v1):", norm_v1)
print("||v1 - v2|| (Norm of v1 - v2):", norm_v1_minus_v2)


||v1|| (Norm of v1): 7.14142842854285
||v1 - v2|| (Norm of v1 - v2): 4.47213595499958


In [7]:
## uppgift 10.2.4

In [8]:
import numpy as np

# Define matrix A (coefficients of x1, x2, x3)
A = np.array([
    [3, 2, 4],
    [2, 3, 8],
    [4, 1, 3],
    [7, 1, 5]
])

# Define vector b (right-hand side of the equations)
b = np.array([7, 4, 11, 9])

# Solve the system of linear equations A * x = b
x = np.linalg.solve(A.T @ A, A.T @ b)

# Verifying the solution using matrix multiplication A * x
Ax = A @ x

# Print results
print("Matrix A:\n", A)
print("Vector b:\n", b)
print("Solution x (values for x1, x2, x3):\n", x)
print("Verification (A * x):\n", Ax)


Matrix A:
 [[3 2 4]
 [2 3 8]
 [4 1 3]
 [7 1 5]]
Vector b:
 [ 7  4 11  9]
Solution x (values for x1, x2, x3):
 [ 2.13691417  4.83412322 -1.89152185]
Verification (A * x):
 [ 8.51290153  3.64402317  7.70721432 10.33491311]


## Exercise 11

In [18]:
v1 = np.arange(4)
v2 = v1[-2:]

print("Original Array (v1):")
print(v1)

print("\nSliced Array (v2):")
print(v2)

# Checking if v2 is a view or copy of v1
print("\nIs v2 a view of v1? (Check base attribute):")
print(v2.base is v1)

# Modify the last element of v2
v2[-1] = 123
print("\nAfter modifying v2:")
print("v1:", v1)
print("v2:", v2)


Original Array (v1):
[0 1 2 3]

Sliced Array (v2):
[2 3]

Is v2 a view of v1? (Check base attribute):
True

After modifying v2:
v1: [  0   1   2 123]
v2: [  2 123]


In [ ]:
# uppgift 10.1.2